layouts:
  [
    { # FC Box
      type: "QGridLayout",
      name: "FCBox",
      label: "FC",
      widgets:
        [
          { position: [0,0], type: "QLabel", label: "Address" },
          { position: [0,1], type: "QComboBox", name: "comboConnFC"},
          { position: [0,2], type: "QPushButton", name: "btnFCRefresh" },
          { position: [0,3], type: "QPushButton", name: "btnFCConnect", span: [1,2] },
          { position: [0,5], type: "QLabel", label: "", stretch: 1 },
          { position: [1,0], type: "QLabel", label: "Rate" },
          { position: [1,1], type: "QComboBox", name: "comboRate" },
          { position: [1,2], type: "QLabelWidget", name: "labelSampling" },
          { position: [1,3], type: "QLabel", label: "Channels" },
          { position: [1,4], type: "QComboBox", name: "comboChannelsFC" }
        ]
    },
    { # DDS Box
      type: "QGridLayout",
      name: "DDSBox",
      label: "DDS",
      widgets:
        [
          { position: [0,0], type: "QLabel", label: "Address" },
          { position: [0,1], type: "QLineEdit", name: "comboConnDDS" },
          { position: [0,2], type: "QPushButton", name: "btnDDSRefresh" },
          { position: [0,3], type: "QPushButton", name: "btnDDSConnect" },
          { position: [0,4], type: "QPushButton", name: "btnDDSEnable" },
          { position: [1,0], type: "QLabel", label: "Frequency [Hz]" },
          { position: [1,1], type: "QLineEdit", name: "freqDDS" },
          { position: [1,2], type: "QLabel", label: "Amplitude [%]" },
          { position: [1,3], type: "QLineEdit", name: "ampDDS" },
          { position: [1,4], type: "QLabel", label: "Phase [deg]" },
          { position: [1,5], type: "QLineEdit", name: "phaseDDS" }
        ]
    },
    { # Stabilizer settings 
      type: "QGridLayout",
      name: "settingsStabBox",
      label: "Stabilisation settings",
      widgets:
      [
        { position: [0,0], type: "QLabelWidget", name: "labelTarget", span: [1,2]  },
        { position: [0,2], type: "QLineEdit", name: "valTarget", span: [1,2] },
        { position: [0,4], type: "QLabel", label: "Target phase [period]", span: [1,2] },
        { position: [0,6], type: "QLineEdit", name: "valTargetPhase" },
        { position: [0,8], type: "QLabel", label: "", colStretch: 1 },
        { position: [1,0], type: "QLabel", label: "Mode" },
        { position: [1,1], type: "QComboBox", name: "comboMode" },
        { position: [1,2], type: "QPushButton", name: "btnSetFilter", span: [1,2] },
        { position: [1,4], type: "QPushButton", name: "btnResetFilter", span: [1,2] },
        { position: [1,6], type: "QLabel", label: "Apply lowpass"},
        { position: [1,7], type: "QCheckBox", name: "checkLowpass" },
        { position: [2,2], type: "QLabel", label: "Frequency lock" },
        { position: [2,3], type: "QLedIndicator", name: "ledLock" },
        { position: [2,4], type: "QLabel", label: "Phase lock" },
        { position: [2,5], type: "QLedIndicator", name: "ledPhaseLock" },
        { position: [2,6], type: "QPushButton", name: "btnLock", span: [1,2] }
      ]
    },
    { # Plot settings
      type: "QHBoxLayout",
      name: "settingsPlot",
      label: "Plot settings",
      widgets: 
      [
        { type: "QLabel", label: "Calculate Allan" },
        { type: "QCheckBox", name: "checkAllan" },
        { type: "QLabel", label: "Lower plot" },
        { type: "QComboBox", name: "comboShow" },
        { type: "QPushButton", name: "btnResetPlot" },
        { type: "QLabel", label: "Autosave data" },
        { type: "WCheckBox", name: "checkAutosave" },
        { type: "stretch", value: 1}
      ]
    }
  ]

mainLayout:
  { # Main layout
    name: "mainLayout",
    type: "QHBoxLayout",
    contents:
      [
        { # Left main box
          name: "leftBox", type: "QVBoxLayout", stretch: 4, contents:
          [
            # FC settings
            { name: "FCGroup", type: "QGroupBox", label: "FC settings", contents: 
              [
                { name: "FCBox", type: "layout", contents: [] }
              ]
            },
            # DDS settings
            { name: "DDSGroup", type: "QGroupBox", label: "DDS settings", contents: 
              [
                { name: "DDSBox", type: "layout", contents: [] }
              ]
            },
            # Stabilizer settings
            { name: "settingsStabGroup", type: "QGroupBox", label: "Stabilization settings", contents:
              [
                { name: "SettingsStabVBox", type: "QVBoxLayout", contents: 
                  [
                    { name: "settingsStabBox", type: "layout", contents: [] },
                    { name: "filters", type: "widget", contents: [] }
                  ]
                }
              ]
            },
            # Allan deviation plot
            { name: "plotAllan", type: "widget", stretch: 1 }
          ]
        },
        { # Right main box
          name: "rightBox", type: "QVBoxLayout", stretch: 6, contents: 
          [
            # Plot settings
            { name: "settingsPlotGroup", type: "QGroupBox", label: "Plot settings", contents:
              [
                { name: "settingsPlot", type: "layout", contents: [] }
              ]
            },
            { name: "plotFrequency", type: "widget", contents: [] },
            { name: "plotStabilizer", type: "widget", contents: [] }
          ] 
        }
      ]
  }