layouts:
  [
    { # ADC Box
      type: "QGridLayout",
      name: "ADCBox",
      label: "ADC",
      widgets:
        [
          { position: [0,0], type: "QLabel", label: "Rate" },
          { position: [0,1], type: "QComboBox", name: "comboRate" },
          { position: [0,2], type: "QLabel", label: "Channels" },
          { position: [0,3], type: "QComboBox", name: "comboChannelsADC" },
          { position: [0,4], type: "QPushButton", name: "btnADCConnect" },
          { position: [0,5], type: "QLabel", label: "", colStretch: 1 },
          { position: [1,0], type: "QLabelWidget", name: "labelSampling", span: [1,2] }
        ]
    },
    { # DAC Box
      type: "QGridLayout",
      name: "DACBox",
      label: "DAC",
      widgets:
        [
          { position: [0,0], type: "QLabel", label: "DAC output [V]" },
          { position: [0,1], type: "QLineEdit", name: "outputDAC" },
          { position: [0,2], type: "QPushButton", name: "btnDACConnect" },
          { position: [0,3], type: "QPushButton", name: "btnDACEnable" },
          { position: [0,4], type: "QLabel", label: "", colStretch: 1 }
        ]
    },
    { # Stabilizer settings 
      type: "QGridLayout",
      name: "settingsStabBox",
      label: "Stabilisation settings",
      widgets:
      [
        { position: [0,0], type: "QLabel", label: "Setpoint [V]", span: [1,2]  },
        { position: [0,2], type: "QLineEdit", name: "valTarget" },
        { position: [0,3], type: "QPushButton", name: "btnSetFilter" },
        { position: [0,4], type: "QPushButton", name: "btnResetFilter" },
        { position: [0,5], type: "QPushButton", name: "btnLock" },
        { position: [0,6], type: "QLabel", label: "", colStretch: 1 },
        { position: [1,0], type: "QLabel", label: "Lock status" },
        { position: [1,1], type: "QLedIndicator", name: "ledLock" },
        { position: [1,2], type: "QLabel", label: "Current filter:" },
        { position: [1,3], type: "QLabelWidget", name: "labelFilter" }
      ]
    },
    { # Plot settings
      type: "QHBoxLayout",
      name: "settingsPlot",
      label: "Plot settings",
      widgets: 
      [
        { type: "QLabel", label: "Calculate Allan" },
        { type: "QCheckBox", name: "checkAllan" },
        { type: "QLabel", label: "Lower plot" },
        { type: "QComboBox", name: "comboShow" },
        { type: "QPushButton", name: "btnResetPlot" },
        { type: "QLabel", label: "Autosave data" },
        { type: "WCheckBox", name: "checkAutosave" },
        { type: "stretch", value: 1}
      ]
    }
  ]

mainLayout:
  { # Main layout
    name: "mainLayout",
    type: "QHBoxLayout",
    contents:
      [
        { # Left main box
          name: "leftBox", type: "QVBoxLayout", stretch: 5, contents:
          [
            # ADC settings
            { name: "ADCGroup", type: "QGroupBox", label: "ADC settings", contents: 
              [
                { name: "ADCBox", type: "layout", contents: [] }
              ]
            },
            # DAC settings
            { name: "DACGroup", type: "QGroupBox", label: "DAC settings", contents: 
              [
                { name: "DACBox", type: "layout", contents: [] }
              ]
            },
            # Stabilizer settings
            { name: "settingsStabGroup", type: "QGroupBox", label: "Stabilization settings", contents:
              [
                { name: "SettingsStabVBox", type: "QVBoxLayout", contents: 
                  [
                    { name: "settingsStabBox", type: "layout", contents: [] },
                    { name: "filters", type: "widget", contents: [] }
                  ]
                }
              ]
            },
            # Allan deviation plot
            { name: "plotAllan", type: "widget", stretch: 1 }
          ]
        },
        { # Right main box
          name: "rightBox", type: "QVBoxLayout", stretch: 5, contents: 
          [
            # Plot settings
            { name: "settingsPlotGroup", type: "QGroupBox", label: "Plot settings", contents:
              [
                { name: "settingsPlot", type: "layout", contents: [] }
              ]
            },
            { name: "plotFrequency", type: "widget", contents: [] },
            { name: "plotStabilizer", type: "widget", contents: [] }
          ] 
        }
      ]
  }
