QLineEdit:
  [
    { name: "valTarget", label: "Target frequency [Hz]", default: "7e6" },
    { name: "freqDDS", label: "DDS frequency [Hz]", default: "2e6" },
    { name: "ampDDS", label: "DDS amplitude", default: "100" },
    { name: "phaseDDS", label: "DDS phase", default: "0" },
    { name: "connDDS", label: "DDS connection address", default: "172.17.32." }
  ]
QPushButton:
  [
    { name: "btnFCConnect", label: "Connect" },
    { name: "btnRefresh", label: "Refresh" },
    { name: "btnLock", label: "Lock" },
    { name: "btnResetFilter", label: "Reset filter" },
    { name: "btnDDSEnable", label: "Enable" },
    { name: "btnDDSConnect", label: "Connect" },
    { name: "btnResetPlot", label: "Reset plot" }
  ]
QComboBox:
  [
    { name: "comboUSB", label: "USB address", contents: [] },
    { name: "comboRate", label: "Rate", contents: ['1ms', '2ms', '5ms', '10ms', '20ms', '50ms', '100ms', '200ms', '500ms', '1s', '2s', '5s', '10s', '20s'] },
    { name: "comboMode", label: "Frequency or phase measurement", contents: ["Frequency", "Phase"] },
    { name: "comboShow", label: "Lower plot what to show", contents: ['Error', 'Control'] }
  ]
QCheckBox:
  [
    { name: "checkLowpass", label: "Apply lowpass" },
    { name: "checkAllan", label: "Calculate Allan deviation" },
    { name: "checkAutosave", label: "Autosave" }
  ]
QLabel:
  [
    { name: "labelSampling", label: "0 Hz" },
    { name: "labelTarget", label: "Target frequency [Hz]" }
  ]
PlotWidget:
  [
    { name: "plotFrequency" },
    { name: "plotStabilizer" },
    { name: "plotAllan" }
  ]
FiltersWidget:
  [
    { name: "filters" }
  ]
LedIndicator:
  [
    { name: "ledLock" }
  ]