QLineEdit:
  [
    { name: "valTarget", label: "Target frequency [Hz]", default: "7e6" },
    { name: "valTargetPhase", label: "Target phase [period]", default: "0" },
    { name: "freqDDS", label: "DDS frequency [Hz]", default: "2e6" },
    { name: "ampDDS", label: "DDS amplitude", default: "100" },
    { name: "phaseDDS", label: "DDS phase", default: "0" }
  ]
QPushButton:
  [
    { name: "btnFCConnect", label: "Connect" },
    { name: "btnFCRefresh", label: "Update list" },
    { name: "btnDDSConnect", label: "Connect" },
    { name: "btnDDSRefresh", label: "Update list" },
    { name: "btnDDSEnable", label: "Enable" },
    { name: "btnSetFilter", label: "Set filter" },
    { name: "btnResetFilter", label: "Reset filters" },
    { name: "btnLock", label: "Lock" },
    { name: "btnResetPlot", label: "Reset plot" }
  ]
QComboBox:
  [
    { name: "comboConnFC", label: "FC address", contents: [] },
    { name: "comboChannelsFC", label: "FC channels", contents: ['1', '2'] },
    { name: "comboRate", label: "Rate", contents: [] },
    { name: "comboConnDDS", label: "DDS address", contents: [] },
    { name: "comboMode", label: "Frequency or phase measurement", contents: ["Frequency", "Phase"] },
    { name: "comboShow", label: "Lower plot what to show", contents: ['Error [Hz]', 'Error [period]', 'Process variable', 'Control'] }
  ]
QCheckBox:
  [
    { name: "checkLowpass", label: "Apply lowpass" },
    { name: "checkAllan", label: "Calculate Allan deviation" },
    { name: "checkAutosave", label: "Autosave" }
  ]
QLabel:
  [
    { name: "labelSampling", label: "0 Hz" },
    { name: "labelTarget", label: "Target frequency [Hz]" }
  ]
PlotWidget:
  [
    { name: "plotFrequency" },
    { name: "plotStabilizer" },
    { name: "plotAllan" }
  ]
FiltersWidget:
  [
    { name: "filters" }
  ]
LedIndicator:
  [
    { name: "ledLock" },
    { name: "ledPhaseLock" }
  ]